### ISSUE TITLE
The Client doesnot work on the current certificate created with localhost credentials

### ISSUE THREAD

**Issue by rohirto** [rohirto/test#7]

**Comment by dhawal2611** [comment]
Need to make the Docker IP into the same subnet so that the network of the whole system becomes same and broker can be started into one of the system and From another systems we need to do pub & sub on the same topic.

**Comment by rohirto** [comment]
Changed the Docker configuration to host mode (docker now shares the same network as the Host machine)

**Comment by rohirto** [comment]
Added the create_certificates script, so that certificates can be dynamically created as the server IP changes
